# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2d23b18caaab34d3c990465c463a62b20f9f3e24bb8aefb5205556e9296769d61ac2573558ac8f50267413d0d9b2bcba4bf71bba2a152a89b8ff74221c03741

test:
  secret_key_base: a8fc7e3aaa575c5e7b8589889306ad154435b471f624c87759be9e66a37ebc9d2e9c1949accc58171a29dbfbcc21d745b4df7d4d49513ee28a9599e9b866c406

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
